### PR TITLE
Fixes gradle project structure

### PR DESCRIPTION
**Pull request by Dragas**
Initially your project is hard to import as it redefines some of the main gradle characteristics. This pull request solves those issues and may serve as a sample further down the line.

### CODE REVIEW

**Comment by Pythonic-Rainbow** [comment]
What is the comment of input.Property?
Also, do I just change the dependency version if I release it?

**Comment by Dragas** [comment]
I was not aware that you need "module name" to compile java 9 modules, hence the kept comments. Refer to https://guides.gradle.org/building-java-9-modules/ when building the modules.

Regarding your question: dependency version of what?

**Comment by Pythonic-Rainbow** [comment]
Like what to do if I want to release a new version of API and Endpooint? dependencies project(':javablox-api') wouldn't work if I release. I will need dependencies 'io.github.rbxapi:javablox-api:1.0.1'. But if I publish them at the same time, Travis can't compile the project because 1.0.1 isn't published yet.

**Comment by Dragas** [comment]
You depend on sibling projects, not external dependencies of your own modules.

**Comment by Pythonic-Rainbow** [comment]
But the entire Endpoint would be packed as a single artifact if I depend on siblings right, I want the user to download two seperate artifact, namely endpoint and api.

**Comment by Dragas** [comment]
You can deploy a single artifact that contains its dependencies, yes. Look into how to compile a fat jar.

**Comment by Dragas** [comment]
Oh I forgot to mention: don't forget to look into difference between `api` and `implementation`. Sometimes you may not want to expose your dependencies.

**Comment by Pythonic-Rainbow** [comment]
hey @Dragas  thanks for your continous reply
if I depend on sibling project, will gradle publish a fat endpoint artifact that has api build in?
Or gradle will smartly resolve dependencies when users depend on endpoint?

**Review by Pythonic-Rainbow — CHANGES_REQUESTED** [review]
Can u rebase your branch please? I've done some updates to allow portable encryption
Then I will very likely to merge it, thanks!

**Review by Pythonic-Rainbow — APPROVED** [review]

**Comment by iranathan** [comment]
:(

**Pull request merged**
